# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true

# Change command timeout from 500 to 1000 ms
command_timeout = 1000

# Change the default prompt format
format = """[╭─](238)$env_var$all[╰─](238)$time$character"""

# Change the default prompt characters
[character]
    success_symbol = "[](bold green)"
    error_symbol = "[](bold red)"

# Shows an icon that should be included by zshrc script based on the distribution or os
[env_var.STARSHIP_DISTRO]
    format = '[$env_value](bold white)'
    variable = "STARSHIP_DISTRO"
    disabled = false

# Show command duration over 10,000 milliseconds (=10 sec)
[cmd_duration]
    min_time = 10_000 
    format = " took [$duration]($style)"

# Shows the username
[username]
    style_user = "bold white"
    style_root = "bold red"
    format = "$user($style) "
    disabled = false
    show_always = true

[time]
    time_format = "%H:%M"
    format = "🕙 $time(238) "
    style = "bright-white"
    disabled = false

[directory]
    truncation_length = 1
    truncation_symbol = "…/"
    home_symbol = " ~"
    read_only_style = "197"
    read_only = "  "
    format = "in [$path]($style)[$read_only]($read_only_style) "

# Main Symbols
    [git_branch]
        symbol = " "
        format = "on [$symbol$branch]($style) "
        truncation_length = 4
        truncation_symbol = "…/"
        style = "bold green"

    [git_commit]
        commit_hash_length = 4
        style = "bold white"

    [git_state]
        format = '[\($state($progress_current of $progress_total)\)]($style) '

    [git_status]
        format = '[$all_status$ahead_behind]($style) '
        style = "bold green"
        conflicted = "(red) "
        up_to_date = " "
        untracked = " ${count} "
        ahead = "⇡${count} "
        diverged = "⇕⇡${ahead_count}⇣${behind_count} "
        behind = "⇣${count} "
        stashed = " ${count} "
        modified = " ${count} "
        staged = '[++\($count\)](green) '
        renamed = "襁 ${count} "
        deleted = " ${count} "

    [python]
        symbol = " "
        format = 'via [${symbol}(${version} )(\($virtualenv\))]($style) '
        style = "yellow bold"
        python_binary = [".venv/bin/python", "python", "python3"]

    [nodejs]
        format = "via [ $version](bold green) "
        
    [rust]
        format = "via [$symbol$version](red bold)"

    [terraform]
        format = "via [ terraform $version]($style) 壟 [$workspace]($style) "

    [vagrant]
        format = "via [ vagrant $version]($style) "

    [docker_context]
        format = "via [ $context](bold blue) "

    [helm]
        format = "via [ $version](bold purple) "

    [ruby]
        format = "via [ $version]($style) "

    [kubernetes]
        format = 'on [ $context\($namespace\)](bold purple) '
        disabled = false
    [kubernetes.context_aliases]
        "clcreative-k8s-staging" = "cl-k8s-staging"
        "clcreative-k8s-production" = "cl-k8s-prod"


# Other Symbols
    [aws]
    symbol = "  "

    [conda]
    symbol = " "

    [dart]
    symbol = " "

    [elixir]
    symbol = " "

    [elm]
    symbol = " "

    [golang]
    symbol = " "

    [hg_branch]
    symbol = " "

    [java]
    symbol = " "

    [julia]
    symbol = " "

    [memory_usage]
    symbol = " "

    [nim]
    symbol = " "

    [nix_shell]
    symbol = " "

    [package]
    symbol = " "
    disabled = true